// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: grpcsrv/v1/grpcsrv.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// event from robot (the body) containing current state
type ClientEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_grpcsrv_v1_grpcsrv_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Say struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Say) Reset() {
	*x = Say{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Say) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Say) ProtoMessage() {}

func (x *Say) ProtoReflect() protoreflect.Message {
	mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Say.ProtoReflect.Descriptor instead.
func (*Say) Descriptor() ([]byte, []int) {
	return file_grpcsrv_v1_grpcsrv_proto_rawDescGZIP(), []int{1}
}

func (x *Say) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Print struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Print) Reset() {
	*x = Print{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Print) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Print) ProtoMessage() {}

func (x *Print) ProtoReflect() protoreflect.Message {
	mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Print.ProtoReflect.Descriptor instead.
func (*Print) Descriptor() ([]byte, []int) {
	return file_grpcsrv_v1_grpcsrv_proto_rawDescGZIP(), []int{2}
}

func (x *Print) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// delay in milliseconds before triggering the action
	// could use the Duration type here, but don't think we need nanosecond
	// precision and the second/nanosecond split complicates things
	Delay int32 `protobuf:"varint,1,opt,name=delay,proto3" json:"delay,omitempty"`
	// Types that are assignable to Action:
	//
	//	*Action_Say
	//	*Action_Print
	Action isAction_Action `protobuf_oneof:"action"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_grpcsrv_v1_grpcsrv_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetDelay() int32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (m *Action) GetAction() isAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *Action) GetSay() *Say {
	if x, ok := x.GetAction().(*Action_Say); ok {
		return x.Say
	}
	return nil
}

func (x *Action) GetPrint() *Print {
	if x, ok := x.GetAction().(*Action_Print); ok {
		return x.Print
	}
	return nil
}

type isAction_Action interface {
	isAction_Action()
}

type Action_Say struct {
	Say *Say `protobuf:"bytes,2,opt,name=say,proto3,oneof"`
}

type Action_Print struct {
	Print *Print `protobuf:"bytes,3,opt,name=print,proto3,oneof"`
}

func (*Action_Say) isAction_Action() {}

func (*Action_Print) isAction_Action() {}

// message from brain to body, instructing the body do take one or more actions
type ServerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Actions []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpcsrv_v1_grpcsrv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_grpcsrv_v1_grpcsrv_proto_rawDescGZIP(), []int{4}
}

func (x *ServerEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerEvent) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_grpcsrv_v1_grpcsrv_proto protoreflect.FileDescriptor

var file_grpcsrv_v1_grpcsrv_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x72, 0x70, 0x63, 0x73, 0x72, 0x76, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x68, 0x65, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x03, 0x53, 0x61, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x1b, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x80, 0x01, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x27, 0x0a, 0x03, 0x73, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x74, 0x68, 0x65, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x53, 0x61, 0x79, 0x48, 0x00, 0x52, 0x03, 0x73, 0x61, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x68, 0x65,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x05, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x68, 0x65, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x5f, 0x0a, 0x0e, 0x54, 0x68, 0x65, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x4d, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1b, 0x2e, 0x74, 0x68, 0x65, 0x73, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x68, 0x65, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x73, 0x72, 0x76, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpcsrv_v1_grpcsrv_proto_rawDescOnce sync.Once
	file_grpcsrv_v1_grpcsrv_proto_rawDescData = file_grpcsrv_v1_grpcsrv_proto_rawDesc
)

func file_grpcsrv_v1_grpcsrv_proto_rawDescGZIP() []byte {
	file_grpcsrv_v1_grpcsrv_proto_rawDescOnce.Do(func() {
		file_grpcsrv_v1_grpcsrv_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcsrv_v1_grpcsrv_proto_rawDescData)
	})
	return file_grpcsrv_v1_grpcsrv_proto_rawDescData
}

var file_grpcsrv_v1_grpcsrv_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpcsrv_v1_grpcsrv_proto_goTypes = []interface{}{
	(*ClientEvent)(nil), // 0: thesocialrobot.ClientEvent
	(*Say)(nil),         // 1: thesocialrobot.Say
	(*Print)(nil),       // 2: thesocialrobot.Print
	(*Action)(nil),      // 3: thesocialrobot.Action
	(*ServerEvent)(nil), // 4: thesocialrobot.ServerEvent
}
var file_grpcsrv_v1_grpcsrv_proto_depIdxs = []int32{
	1, // 0: thesocialrobot.Action.say:type_name -> thesocialrobot.Say
	2, // 1: thesocialrobot.Action.print:type_name -> thesocialrobot.Print
	3, // 2: thesocialrobot.ServerEvent.actions:type_name -> thesocialrobot.Action
	0, // 3: thesocialrobot.TheSocialRobot.EventStream:input_type -> thesocialrobot.ClientEvent
	4, // 4: thesocialrobot.TheSocialRobot.EventStream:output_type -> thesocialrobot.ServerEvent
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpcsrv_v1_grpcsrv_proto_init() }
func file_grpcsrv_v1_grpcsrv_proto_init() {
	if File_grpcsrv_v1_grpcsrv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcsrv_v1_grpcsrv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcsrv_v1_grpcsrv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Say); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcsrv_v1_grpcsrv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Print); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcsrv_v1_grpcsrv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcsrv_v1_grpcsrv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpcsrv_v1_grpcsrv_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Action_Say)(nil),
		(*Action_Print)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcsrv_v1_grpcsrv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcsrv_v1_grpcsrv_proto_goTypes,
		DependencyIndexes: file_grpcsrv_v1_grpcsrv_proto_depIdxs,
		MessageInfos:      file_grpcsrv_v1_grpcsrv_proto_msgTypes,
	}.Build()
	File_grpcsrv_v1_grpcsrv_proto = out.File
	file_grpcsrv_v1_grpcsrv_proto_rawDesc = nil
	file_grpcsrv_v1_grpcsrv_proto_goTypes = nil
	file_grpcsrv_v1_grpcsrv_proto_depIdxs = nil
}
